// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzoLxRvUBzCW5Kp47XIwG1yDQ2c-N3-8',
    appId: '1:652895887444:web:e65a483987317aa0db0dc1',
    messagingSenderId: '652895887444',
    projectId: 'flutter--sns',
    authDomain: 'flutter--sns.firebaseapp.com',
    storageBucket: 'flutter--sns.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcUElfwTe47LVnPJLKhzR4Fd1yPr4Scrk',
    appId: '1:652895887444:android:d0ca7bff9d346e14db0dc1',
    messagingSenderId: '652895887444',
    projectId: 'flutter--sns',
    storageBucket: 'flutter--sns.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVnbTdYWEKW9hl-8W01BdNLwzt9lpXPh0',
    appId: '1:652895887444:ios:d23ab8da5e6cfb8ddb0dc1',
    messagingSenderId: '652895887444',
    projectId: 'flutter--sns',
    storageBucket: 'flutter--sns.appspot.com',
    iosClientId: '652895887444-pi4k6avfr13vtr29vuj70l3im4idnvlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVnbTdYWEKW9hl-8W01BdNLwzt9lpXPh0',
    appId: '1:652895887444:ios:d23ab8da5e6cfb8ddb0dc1',
    messagingSenderId: '652895887444',
    projectId: 'flutter--sns',
    storageBucket: 'flutter--sns.appspot.com',
    iosClientId: '652895887444-pi4k6avfr13vtr29vuj70l3im4idnvlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSns',
  );
}
